<?php

namespace AppBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRecommended(){

        $qb=$this->getEntityManager()
            ->createQuery("SELECT e.idEvent,e.nom,e.type,e.dateDebut,e.url,e.rate
                            FROM  AppBundle:Evenement e 
                            ORDER BY e.rate DESC" );

        return $qb->getResult();

    }





}