<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findciteby($idcite){
        $qb=$this->getEntityManager()
            ->createQuery("SELECT u 
                            FROM AppBundle:Logement u JOIN AppBundle:Cite c WITH u.id_cite = c.id_cite
                            WHERE c.id_cite='$idcite'");

        return $qb->getResult();
    }

    public function findreservation($iduser){
        $qb=$this->getEntityManager()
            ->createQuery("SELECT u 
                            FROM AppBundle:Logement u JOIN AppBundle:ReservationLogement r WITH u.id = r.idLogement
                            WHERE r.idUser='$iduser'");

        return $qb->getResult();
    }





}