<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Equipement;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAvg($id)
    {
        // automatically knows to select Products
        // the "p" is an alias you'll use in the rest of the query
        $qb = $this->createQueryBuilder('e')
            ->innerJoin(Equipement::class,'eq', 'WITH', 'eq = e.equipement' )
            ->select('avg(e.rate)')
            ->where('eq.idEq = :id')
            ->setParameter(':id',$id)
            ->getQuery();

        return $qb->execute();

        // to get just one result:
        // $product = $qb->setMaxResults(1)->getOneOrNullResult();
    }
}
