<?php

namespace AppBundle\Repository;

/**
 * UnwantedwordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnwantedwordsRepository extends \Doctrine\ORM\EntityRepository
{


}
